# Copyright (c) Datalayer, Inc. https://datalayer.io
# Distributed under the terms of the MIT License.

name: datalayer
channels:
  - conda-forge
dependencies:
  - configurable-http-proxy
  - jq
  - nodejs=18.15.0
  - pip
  - python=3.11
  - yarn=3.5.0
  - pip:
    - build
    - hatch
    - jupyter-packaging
    - jupyterlab==4.1.0b0
    - jupyterhub==4.0.3
